"""More Tables testing

Revision ID: 8501c794ee28
Revises: dce682a6633f
Create Date: 2026-09-13 12:02:42.935870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8501c794ee28'
down_revision = 'dce682a6633f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('sets_acquired', sa.String(length=300), nullable=True),
    sa.Column('account_worth', sa.Integer(), nullable=True),
    sa.Column('tier', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['UserInfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('decks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('sets_acquired', sa.VARCHAR(length=300), nullable=True),
    sa.Column('account_worth', sa.INTEGER(), nullable=True),
    sa.Column('tier', sa.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['UserInfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Decks')
    # ### end Alembic commands ###
