"""Testing Tables

Revision ID: afe69ff330fe
Revises: 8501c794ee28
Create Date: 2026-09-13 12:06:08.567943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe69ff330fe'
down_revision = '8501c794ee28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserInfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=88), nullable=False),
    sa.Column('password_h', sa.String(length=256), nullable=False),
    sa.Column('equipped_card_deck', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('sets_acquired', sa.String(length=300), nullable=True),
    sa.Column('account_worth', sa.Integer(), nullable=True),
    sa.Column('tier', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['UserInfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Decks')
    op.drop_table('UserInfo')
    # ### end Alembic commands ###
