"""testing my tables

Revision ID: dce682a6633f
Revises: 
Create Date: 2026-09-13 00:45:22.583841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dce682a6633f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserInfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=88), nullable=False),
    sa.Column('password_h', sa.String(length=256), nullable=False),
    sa.Column('equipped_card_deck', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('sets_acquired', sa.String(length=300), nullable=True),
    sa.Column('account_worth', sa.Integer(), nullable=True),
    sa.Column('tier', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['UserInfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decks')
    op.drop_table('UserInfo')
    # ### end Alembic commands ###
